---
- name: "[RUN] Define a Postgresql container for Ansible Tower"
  podman_container:
    name: '{{ tower_postgresql_container_name }}'
    image: '{{ postgresql_image }}'
    state: started
    log_driver: journald
    ports:
      - 5432:5432
    mount: "{{ postgresql_persistent|bool|ternary(postgresql_mount_statement, omit) }}"
    env:
      POSTGRESQL_USER: '{{ postgresql_user }}'
      POSTGRESQL_PASSWORD: '{{ postgresql_password }}'
      POSTGRESQL_DATABASE: '{{ postgresql_database }}'
