---
# Yes, RHSM will need to be used for the building of this image. It will be
#   deregistered and no subscriptions will be permanently consumed.
rhsm_username: USERNAME
rhsm_password: 'PASSWORD'

# You can change this to, for example, `../tmp/tower_pgsql` to keep it in the
#   project directory
postgresql_persistent_dir: /tmp/tower_pgsql

# You should absolutely 100% definitely change this
tower_admin_password: password

# These can be changed if you like, or left alone for the module_defaults
tower_http_port: "8080"
tower_https_port: "8443"

# You can provide the path to a json file that contains your Tower license to
#   have it automatically entitled.
# This path is relative to the playbooks, so `../tower_license.json` is in the
#   project root.
# tower_license: ../tower_license.json

# If you've provided the license and have accepted the Ansible Tower EULA you
#   may change this key to accept it automatically on the Tower instance
eula_status:
  eula_accepted: false

# You can change these if you would like to, for example, spin up multiple
#   copies of tower simultaneously. You can also override them with just
#   extra-vars if you prefer.
tower_container_name: ansible-tower
tower_container_image_name: ansible-tower
tower_postgresql_container_name: ansible-tower-postgresql
