---
# Yes, RHSM will need to be used for the building of this image. It will be
#   deregistered and no subscriptions will be permanently consumed.
rhsm_username: USERNAME
rhsm_password: 'PASSWORD'

# You can change this to, for example, `../tmp/tower_pgsql` to keep it in the
#   project directory
postgresql_persistent_dir: /tmp/tower_pgsql

# You should absolutely 100% definitely change this
tower_admin_password: password

# This can be changed if you like, or left alone for the module_defaults
tower_https_port: "8443"

# You can change these if you would like to, for example, spin up multiple
#   copies of tower simultaneously. You can also override them with just
#   extra-vars if you prefer.
tower_container_name: ansible-tower
tower_container_image_name: ansible-tower

# If you want trusted TLS, you can provide these files to include them
#   automatically, otherwise you get self-signed
# web_server_ssl_cert: ../tower.cert
# web_server_ssl_key: ../tower.key
