---
- name: >
    Stop Ansible Tower, the dependent postgresql container, and remove all
    images
  hosts: podman_host
  vars:
    deployment_state: absent
  roles:
    - tower-container
    - tower-postgresql-container
