---
- name: "[BUILD] Ensure latest Ansible Tower setup is downloaded"
  import_tasks: download.yml

- name: "[BUILD] Ensure latest Ansible Tower setup is modified"
  import_tasks: modify.yml

- name: "[BUILD] Ensure Ansible Tower has been packaged, if updated"
  include_tasks: package.yml
  when:
    - setup_unarchive is defined
    - setup_unarchive.changed
