---
- name: "[BUILD] Create folder"
  file:
    path: '{{ postgresql_persistent_dir }}'
    state: directory
  when: postgresql_persistent|bool

- name: "[BUILD] Check folder owner"
  shell: podman unshare stat -c '%u:%g' "{{ postgresql_persistent_dir }}"
  changed_when: false
  register: persistent_dir_owner
  when: postgresql_persistent|bool

- name: "[BUILD] Set owner for folder"
  shell: podman unshare chown 26:26 "{{ postgresql_persistent_dir }}"
  when:
    - postgresql_persistent|bool
    - persistent_dir_owner.stdout != '26:26'

- name: "[BUILD] Ensure latest Ansible Tower setup is downloaded"
  import_tasks: download.yml

- name: "[BUILD] Ensure latest Ansible Tower setup is modified"
  import_tasks: modify.yml

- name: "[BUILD] Check for completed image"
  shell: podman images -qf reference='{{ tower_container_image_name }}'
  register: tower_images
  changed_when: false

- name: "[BUILD] Ensure Ansible Tower has been packaged, if updated"
  include_tasks: package.yml
  when:
    - tower_images.stdout.strip() == "" or setup_unarchive is defined
    - tower_images.stdout.strip() == "" or setup_unarchive.changed
