---
- import_tasks: download.yml

- import_tasks: modify.yml

- name: "[BUILD] Stage getty override"
  copy:
    content: |
      [Service]
      ExecStart=
      ExecStartPre=-/usr/bin/sed -i '/pam_loginuid.so/d' /etc/pam.d/login
      ExecStart=-/sbin/agetty --autologin root --noclear --keep-baud console 115200 38400 9600 vt
    dest: ../tmp/getty.conf

- name: "[BUILD] Template files needed for build"
  template:
    src: '{{ item.name }}.j2'
    dest: ../tmp/{{ item.name }}
    mode: '{{ item.mode|default(omit) }}'
  loop:
    - name: tower-install.service
    - name: Dockerfile
    - name: rhsm-register.sh
      mode: '0755'

- name: "[BUILD] Template Tower setup inventory"
  template:
    src: inventory.j2
    dest: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/inventory

- name: "[BUILD] Build the Tower container"
  podman_image:
    name: tower
    path: ../tmp/
    username: '{{ registry_username|default(omit) }}'
    password: '{{ registry_password|default(omit) }}'
    build:
      format: docker
      extra_args: --ulimit=nofile=4096:4096
