---
- name: "[BUILD] Ensure latest Ansible Tower setup is downloaded"
  import_tasks: download.yml

- name: "[BUILD] Ensure latest Ansible Tower setup is modified"
  import_tasks: modify.yml

- name: "[BUILD] Check for completed image"
  shell: podman images -qf reference='{{ tower_container_image_name }}'
  register: tower_images
  changed_when: false

- name: "[BUILD] Ensure Ansible Tower has been packaged, if updated"
  include_tasks: package.yml
  when:
    - tower_images.stdout.strip() != "" or setup_unarchive is defined
    - tower_images.stdout.strip() != "" or setup_unarchive.changed
