---
- name: "[DESTROY] Destroy the Tower container"
  podman_container:
    name: '{{ tower_container_name }}'
    state: absent

- name: "[DESTROY] Gather all image tags for Tower"
  shell: podman images -f reference='{{ tower_container_image_name }}' --format='{{ "{{" }}.Tag{{ "}}" }}'
  register: tower_tags
  changed_when: false
  when: destroy_tower_version is undefined

- name: "[DESTROY] Destroy the Tower container image"
  podman_image:
    name: '{{ tower_container_image_name }}'
    tag: '{{ item }}'
    state: absent
  loop: '{{ tower_tags.stdout_lines }}'

- name: "[DESTROY] Remove everything in tmp"
  file:
    path: '{{ item }}'
    state: absent
  with_lines:
    - 'find ../tmp/ -mindepth 1 -maxdepth 1 ! -name .gitkeep'

- name: "[DESTROY] Untrust/remove ansible GPG key"
  shell: |
    if gpg --list-keys |& grep -qF security@ansible.com; then
      gpg --batch --delete-keys --yes security@ansible.com
      echo changed
    else
      echo ok
    fi
  register: delete_keys
  changed_when: '"changed" in delete_keys.stdout_lines'
