---
- name: Destroy the Tower container
  podman_container:
    name: tower
    state: absent

- name: Destroy the Tower container image
  podman_image:
    name: tower
    state: absent

- name: Remove everything in tmp
  file:
    path: '{{ item }}'
    state: absent
  with_lines:
    - 'find ../tmp/ -mindepth 1 -maxdepth 1 ! -name .gitkeep'

- name: Untrust/remove ansible GPG key
  shell: |
    if gpg --list-keys |& grep -qF security@ansible.com; then
      gpg --batch --delete-keys --yes security@ansible.com
      echo changed
    else
      echo ok
    fi
  register: delete_keys
  changed_when: '"changed" in delete_keys.stdout_lines'

