---
- name: Ensure deployment of Tower
  include_tasks: build.yml
  when: deployment_state == "present"
- name: Ensure absence of Tower
  include_tasks: destroy.yml
  when: deployment_state == "absent"
