---
- name: "[MODIFY] Don't try to restart cgconfig"
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/awx_install/tasks/tasks.yml
    regexp: '^\s*state: restarted'
    state: absent

- name: "[MODIFY] Correct booleans for lack of ipv6 support"
  replace:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/nginx/templates/nginx.conf
    regexp: '^(.*)if ansible_all_ipv6_addresses \!= \[\](.*)$'
    replace: '\1if ansible_all_ipv6_addresses is defined and ansible_all_ipv6_addresses != []\2'

- name: "[MODIFY] Unregister and disable tower-install after setup"
  replace:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/setup.sh
    regexp: '{{ "exit ${RC}"|regex_escape() }}'
    replace: |
      subscription-manager unregister
      systemctl disable tower-install.service
      exit $RC

- name: "[MODIFY] Change locale for pgsql config"
  replace:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/postgres/templates/postgresql.conf.j2
    regexp: 'en_US\.UTF-8'
    replace: 'C.utf8'

- name: "[MODIFY] Allow templating pgsql configs on bind mount"
  replace:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/postgres/tasks/conf.yml
    regexp: '^  (copy|template):$'
    replace: |2-
        \1: # modified
          unsafe_writes: yes

- name: "[MODIFY] Tweak installer template/copy locations"
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/postgres/vars/RedHat-8.yml
    regexp: "^pg_conf_dir: '/var/lib/pgsql/data'$"
    line: 'pg_conf_dir: /tmp'

- name: "[MODIFY] Clean up all pgsql files afterwards"
  blockinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/postgres/tasks/conf.yml
    insertbefore: Create unix socket directory
    block: |
      - name: "[HACK] move things from /tmp"
        shell: |
          [ -f /tmp/{{"{{"}} item {{"}}"}} ] && mv /tmp/{{"{{"}} item {{"}}"}} /var/lib/pgsql/data/ ||:
        loop:
          - server.key
          - server.crt
          - pg_hba.conf
          - postgresql.conf

- name: "[MODIFY] Correct redis service module"
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/redis/tasks/tasks.yml
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
  - regexp: "^  service:$"
    line: "  systemd:"
  - regexp: "^    state: restarted$"
    line: ""

- name: "[MODIFY] Add a specific section to just manually start redis"
  blockinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/redis/tasks/tasks.yml
    block: |
      - name: "[HACK] start redis"
        shell: systemctl start redis

- name: "[MODIFY] Hack up the postgres start"
  blockinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/postgres/tasks/init.yml
    marker: "{mark}"
    marker_begin: '    creates: "{{ "{{" }} pg_conf_dir {{ "}}" }}/PG_VERSION"'
    marker_end: '- name: Wait for PostgreSQL to start if it wasnt'
    block: |+

      - name: Make sure PostgreSQL is started
        shell: systemctl start postgresql
        register: postgresql_start

- name: "[MODIFY] Hack up the postgres restart"
  blockinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/postgres/tasks/conf.yml
    marker: "{mark}"
    marker_begin: "    setype: 'lib_t'"
    marker_end: "- name: wait for postgresql restart"
    block: |+

      - name: restart postgresql when authentication settings changed
        shell: systemctl restart postgresql
        when: pg_hba_conf is changed or pg_general_conf is changed
        register: postgresql_restart

- name: "[MODIFY] Hack up the supervisord stop"
  blockinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/awx_install/tasks/tasks.yml
    marker: "{mark}"
    marker_begin: "    - restart supervisor"
    marker_end: "- name: Wait for supervisor to stop."
    block: |+

      - name: Stop supervisor
        shell: systemctl stop supervisord

- name: "[MODIFY] Don't start supervisord"
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/supervisor/tasks/tasks.yml
    regexp: "^    state: started$"
    state: absent

- name: "[MODIFY] Start supervisord with shell"
  blockinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/supervisor/tasks/tasks.yml
    marker: "{mark}"
    marker_begin: "    enabled: yes"
    marker_end: "- name: Wait for the supervisor socket"
    block: |+

      - name: Start supervisor
        shell: systemctl start supervisord

- name: "[MODIFY] Don't start nginx"
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/nginx/tasks/tasks.yml
    regexp: "^    state: started$"
    state: absent

- name: "[MODIFY] Restart nginx with shell"
  copy:
    dest: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/nginx/handlers/main.yml
    content: |
      ---
      - name: restart nginx
        shell: systemctl restart nginx

- name: "[MODIFY] Restart supervisor with shell"
  copy:
    dest: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/supervisor/handlers/main.yml
    content: |
      ---
      - name: restart supervisor
        debug:
          msg: Restarting supervisor.
        changed_when: true
        notify:
          - Stop supervisor.
          - Wait for supervisor to stop.
          - Start supervisor.

      - name: Stop supervisor.
        shell: systemctl stop supervisord

      - name: Wait for supervisor to stop.
        stat:
          path: '/var/run/supervisor/supervisor.sock'
        register: result
        until: not result.stat.exists
        retries: 10
        delay: 2

      - name: Start supervisor.
        shell: systemctl start supervisord
