---
- name: "[MODIFY] Don't try to restart cgconfig"
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/awx_install/tasks/tasks.yml
    regexp: '^\s*state: restarted'
    state: absent

- name: "[MODIFY] Correct booleans for lack of ipv6 support"
  replace:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/nginx/templates/nginx.conf
    regexp: '^(.*)if ansible_all_ipv6_addresses \!= \[\](.*)$'
    replace: '\1if ansible_all_ipv6_addresses is defined and ansible_all_ipv6_addresses != []\2'

- name: "[MODIFY] Unregister and disable tower-install after setup"
  replace:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/setup.sh
    regexp: '{{ "exit ${RC}"|regex_escape() }}'
    replace: |
      subscription-manager unregister
      systemctl disable tower-install.service
      exit $RC
