---
- name: Don't try to restart cgconfig
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/awx_install/tasks/tasks.yml
    regexp: '^\s*state: restarted'
    state: absent

- name: Correct booleans for lack of ipv6 support
  lineinfile:
    path: ../tmp/ansible-tower-setup-{{ ansible_tower_version }}/roles/nginx/templates/nginx.conf
    regexp: '^(.*)if ansible_all_ipv6_addresses \!= \[\](.*)$'
    line: '\1if ansible_all_ipv6_addresses is defined and ansible_all_ipv6_addresses != []\2'
    backrefs: yes
  register: fix_ipv6
  until: not fix_ipv6.changed
