---
- name: "[RUN] Start the Tower container"
  podman_container:
    state: started
    name: '{{ tower_container_name }}'
    image: '{{ tower_container_image_name }}:{{ ansible_tower_version }}'
    log_driver: journald
    rm: true
    interactive: true
    tty: true
    stop_signal: 3
    ports:
      - '{{ tower_https_port|default("8443") }}:443'
    read_only_tmpfs: false
    tmpfs:
      /tmp: rw,nosuid,nodev

- name: "[RUN] Wait for Tower to come up"
  uri:
    url: "https://{{ ansible_host }}:{{ tower_https_port }}/api/v2/ping/"
    follow_redirects: none
    method: GET
    user: admin
    password: '{{ tower_admin_password }}'
    validate_certs: false
  register: _result
  until: _result.json is defined
  retries: 120
  delay: 5
