---
- name: Start the Tower container
  podman_container:
    state: started
    name: tower
    image: tower:latest
    log_driver: journald
    rm: true
    interactive: true
    tty: true
    ports:
      - '{{ tower_http_port|default("8080") }}:80'
      - '{{ tower_https_port|default("8443") }}:443'
    read_only_tmpfs: false
    tmpfs:
      /tmp: rw,nosuid,nodev
    security_opt:
      - label=type:container_userns_t

- name: Wait for Tower to come up from installation
  uri:
    url: "https://{{ ansible_host }}:{{ tower_https_port }}/api/v2/ping/"
    follow_redirects: none
    method: GET
    user: admin
    password: '{{ tower_admin_password }}'
    validate_certs: false
  register: _result
  until: _result.json is defined
  retries: 60
  delay: 5
